# Generated by Django 4.2.5 on 2023-10-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "Catgories",},
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Artificial", "Artificial"), ("Natural", "Natural")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                (
                    "seasonality",
                    models.CharField(
                        choices=[
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Autumn", "Autumn"),
                            ("Winter", "Winter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
                ("image", models.ImageField(upload_to="flower_images")),
                ("vase_life", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flower.category",
                    ),
                ),
            ],
        ),
    ]
