# Generated by Django 4.2.3 on 2023-11-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_alter_flower_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='origin',
        ),
    ]
