# Generated by Django 4.2.3 on 2023-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_remove_flower_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='origin',
            field=models.CharField(default='india', max_length=100),
        ),
    ]
