# Generated by Django 4.2.3 on 2023-11-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_initial'),
        ('flower', '0005_flower_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('placed', 'placed'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='placed', max_length=20)),
                ('payment_method', models.CharField(choices=[('placed', 'placed'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.address')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.flower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
