# Generated by Django 4.2.3 on 2023-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.CharField(default='good flower', max_length=1000),
        ),
    ]
