# Generated by Django 4.2.5 on 2023-10-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Flower",),
    ]
