# Generated by Django 4.2.3 on 2023-11-27 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_delete_flower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=125)),
                ('house_address', models.CharField(max_length=250)),
                ('street_address', models.CharField(max_length=300)),
                ('landmark', models.CharField(max_length=155)),
                ('city', models.CharField(max_length=155)),
                ('state', models.CharField(max_length=155)),
                ('country', models.CharField(max_length=155)),
                ('zip', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
